package interfaz;

import clases.Cuenta;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author baltamar
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    long identificacion;
    long numCuenta;
    Cuenta c;

    public Principal() {
        initComponents();
        cmdInteres.setEnabled(false);
        cmdConsignar.setEnabled(false);
        cmdMostrar.setEnabled(false);
        cmdRetirar.setEnabled(false);
        cmdMostrar.setEnabled(false);
        cmdLimpiar.setEnabled(false);
        txtResultados.setEnabled(false);
        cmdIngresar.setEnabled(false);
        txtNumCuentaIngresar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtIdentificacion = new javax.swing.JTextField();
        cmdRegistrar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtSaldoInicial = new javax.swing.JTextField();
        txtInteresAnual = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtNumCuenta = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        cmdIngresar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtNumCuentaIngresar = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        cmdInteres = new javax.swing.JButton();
        cmdConsignar = new javax.swing.JButton();
        cmdRetirar = new javax.swing.JButton();
        cmdMostrar = new javax.swing.JButton();
        cmdLimpiar = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtResultados = new javax.swing.JTextArea();
        lblSaludar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("CUENTA DE AHORROS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, -1, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Registro"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Identificación:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        txtIdentificacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIdentificacionKeyTyped(evt);
            }
        });
        jPanel2.add(txtIdentificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 130, -1));

        cmdRegistrar.setText("Registrar");
        cmdRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdRegistrarActionPerformed(evt);
            }
        });
        jPanel2.add(cmdRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, -1, -1));

        jLabel3.setText("Nombre:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 20, 50, -1));

        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });
        jPanel2.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 130, -1));

        jLabel5.setText("Saldo Inicial:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel6.setText("Interes Anual:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));
        jPanel2.add(txtSaldoInicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 130, -1));
        jPanel2.add(txtInteresAnual, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 130, -1));

        jLabel7.setText("No. cuenta:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        txtNumCuenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumCuentaKeyTyped(evt);
            }
        });
        jPanel2.add(txtNumCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 130, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 410, 180));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Ingreso"));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmdIngresar.setText("Ingresar");
        cmdIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdIngresarActionPerformed(evt);
            }
        });
        jPanel3.add(cmdIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 80, -1));

        jLabel4.setText("No. cuenta:");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        txtNumCuentaIngresar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumCuentaIngresarKeyTyped(evt);
            }
        });
        jPanel3.add(txtNumCuentaIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 130, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 410, 60));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Opciones"));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmdInteres.setText("Aplicar Interes");
        cmdInteres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdInteresActionPerformed(evt);
            }
        });
        jPanel5.add(cmdInteres, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 110, -1));

        cmdConsignar.setText("Consignar");
        cmdConsignar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdConsignarActionPerformed(evt);
            }
        });
        jPanel5.add(cmdConsignar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 110, -1));

        cmdRetirar.setText("Retirar");
        cmdRetirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdRetirarActionPerformed(evt);
            }
        });
        jPanel5.add(cmdRetirar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 110, -1));

        cmdMostrar.setText("Mostrar");
        cmdMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdMostrarActionPerformed(evt);
            }
        });
        jPanel5.add(cmdMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 110, -1));

        cmdLimpiar.setText("Limpiar");
        cmdLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdLimpiarActionPerformed(evt);
            }
        });
        jPanel5.add(cmdLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 110, -1));

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 130, 250));

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Resultados"));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtResultados.setEditable(false);
        txtResultados.setColumns(20);
        txtResultados.setRows(5);
        txtResultados.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jScrollPane1.setViewportView(txtResultados);

        jPanel6.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 210, 200));

        jPanel4.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 250, 250));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 410, 260));

        lblSaludar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblSaludar.setForeground(new java.awt.Color(0, 204, 51));
        jPanel1.add(lblSaludar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 250, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdentificacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdentificacionKeyTyped
        char c = evt.getKeyChar();

        if (!Character.isDigit(c)) {
            getToolkit().beep();

            evt.consume();
        }

    }//GEN-LAST:event_txtIdentificacionKeyTyped

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        char c = evt.getKeyChar();

        if (Character.isDigit(c)) {
            getToolkit().beep();

            evt.consume();
        }
    }//GEN-LAST:event_txtNombreKeyTyped

    private void cmdRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdRegistrarActionPerformed
        String nombre;
        double saldoIncial, interesAnual;

        if (txtNombre.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese su nombre por favor", "Atención", JOptionPane.INFORMATION_MESSAGE);
            txtNombre.requestFocusInWindow();
        } else if (txtIdentificacion.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese el numuero de identificacion por favor", "Atención", JOptionPane.INFORMATION_MESSAGE);
            txtIdentificacion.requestFocusInWindow();
        } else if (txtNumCuenta.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese el numuero de cuenta por favor", "Atención", JOptionPane.INFORMATION_MESSAGE);
            txtNumCuenta.requestFocusInWindow();
        } else if (txtSaldoInicial.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese un saldo inicial a su cuenta por favor", "Atención", JOptionPane.INFORMATION_MESSAGE);
            txtSaldoInicial.requestFocusInWindow();
        } else if (txtInteresAnual.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese el interes anual por favor", "Atención", JOptionPane.INFORMATION_MESSAGE);
            txtInteresAnual.requestFocusInWindow();
        } else {

            nombre = txtNombre.getText();
            identificacion = Long.parseLong(txtIdentificacion.getText());
            numCuenta = Long.parseLong(txtNumCuenta.getText());
            saldoIncial = Double.parseDouble(txtSaldoInicial.getText());
            interesAnual = Double.parseDouble(txtInteresAnual.getText());

            c = new Cuenta(nombre, numCuenta, identificacion, saldoIncial, interesAnual);

            JOptionPane.showMessageDialog(this, "Registro exitoso", "INFORMACIÓN", JOptionPane.INFORMATION_MESSAGE);
            txtIdentificacion.setText("");
            txtNombre.setText("");
            txtNumCuenta.setText("");
            txtSaldoInicial.setText("");
            txtInteresAnual.setText("");
            txtNumCuentaIngresar.setText("");

            cmdIngresar.setEnabled(true);
            txtNumCuentaIngresar.setEnabled(true);
            txtNumCuentaIngresar.requestFocusInWindow();
        }
    }//GEN-LAST:event_cmdRegistrarActionPerformed

    private void cmdIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdIngresarActionPerformed

        if (txtNumCuentaIngresar.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese su numero de cuenta por favor", "Atención", JOptionPane.INFORMATION_MESSAGE);
            txtNumCuentaIngresar.requestFocusInWindow();
        } else if (Long.parseLong(txtNumCuentaIngresar.getText()) == (c.getNumero_cuenta())) {
            lblSaludar.setText("Bienvenido: " + c.getNombre());
            JOptionPane.showMessageDialog(this, "Ingreso exitoso");

            cmdIngresar.setEnabled(false);
            cmdConsignar.setEnabled(true);
            cmdRetirar.setEnabled(true);
            cmdMostrar.setEnabled(true);
            cmdLimpiar.setEnabled(true);
            cmdInteres.setEnabled(true);
            txtResultados.setEnabled(true);
        } else {
            JOptionPane.showMessageDialog(this, "Usuario No Valido");
            txtNumCuentaIngresar.requestFocusInWindow();
            txtNumCuentaIngresar.selectAll();
        }
    }//GEN-LAST:event_cmdIngresarActionPerformed

    private void cmdConsignarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdConsignarActionPerformed
        double consiginacion = 0;
        int sw, res;

        do {
            sw = 1;
            try {
                consiginacion = Double.parseDouble(JOptionPane.showInputDialog(this, "Ingrese el valor que desea consignar en su cuenta"));
            } catch (NullPointerException e) {
                res = JOptionPane.showConfirmDialog(this, "¿Seguro que deseas salir?", "salir", JOptionPane.YES_NO_OPTION);

                if (res == 0) {
                    sw = 1;

                } else {
                    sw = 0;
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Valor no valido", "Error", JOptionPane.ERROR_MESSAGE);
                sw = 0;
            }

        } while (sw == 0);

        c.consignar(consiginacion);
        

    }//GEN-LAST:event_cmdConsignarActionPerformed

    private void cmdRetirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdRetirarActionPerformed
        double retiro = 0;
        int sw = 1, res;

        do {
            sw = 1;
            try {
                retiro = Double.parseDouble(JOptionPane.showInputDialog(this, "Ingrese el valor que desea consignar en su cuenta"));
            } catch (NullPointerException e) {
                res = JOptionPane.showConfirmDialog(this, "¿Seguro que deseas salir?", "salir", JOptionPane.YES_NO_OPTION);

                if (res == 0) {
                    sw = 1;

                } else {
                    sw = 0;
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Valor no valido", "Error", JOptionPane.ERROR_MESSAGE);
                sw = 0;
            }

        } while (sw == 0);

        c.retirar(retiro);
        
    }//GEN-LAST:event_cmdRetirarActionPerformed

    private void cmdInteresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdInteresActionPerformed

        c.aplicarInteres();
    }//GEN-LAST:event_cmdInteresActionPerformed

    private void cmdMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdMostrarActionPerformed
        txtResultados.setText("");

        txtResultados.setText(c.mostrar());

    }//GEN-LAST:event_cmdMostrarActionPerformed

    private void cmdLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdLimpiarActionPerformed

        txtResultados.setText("");
        txtIdentificacion.setText("");
        txtInteresAnual.setText("");
        txtNombre.setText("");
        txtSaldoInicial.setText("");
        txtNumCuenta.setText("");
        txtNumCuentaIngresar.setText("");
    }//GEN-LAST:event_cmdLimpiarActionPerformed

    private void txtNumCuentaIngresarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumCuentaIngresarKeyTyped
        char c = evt.getKeyChar();

        if (!Character.isDigit(c)) {
            getToolkit().beep();

            evt.consume();
        }    }//GEN-LAST:event_txtNumCuentaIngresarKeyTyped

    private void txtNumCuentaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumCuentaKeyTyped
        char c = evt.getKeyChar();

        if (!Character.isDigit(c)) {
            getToolkit().beep();

            evt.consume();
        }
    }//GEN-LAST:event_txtNumCuentaKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdConsignar;
    private javax.swing.JButton cmdIngresar;
    private javax.swing.JButton cmdInteres;
    private javax.swing.JButton cmdLimpiar;
    private javax.swing.JButton cmdMostrar;
    private javax.swing.JButton cmdRegistrar;
    private javax.swing.JButton cmdRetirar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblSaludar;
    private javax.swing.JTextField txtIdentificacion;
    private javax.swing.JTextField txtInteresAnual;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNumCuenta;
    private javax.swing.JTextField txtNumCuentaIngresar;
    private javax.swing.JTextArea txtResultados;
    private javax.swing.JTextField txtSaldoInicial;
    // End of variables declaration//GEN-END:variables
}
